### ISSUE TITLE
101 Stupid Help

### ISSUE THREAD

**Issue by FalconLorenzo** [jacobian/overcast-sonos#10]
So, this is awkward. I would like to install this, but I find the instructions to be obtuse and not written with the average person in mind. I have not installed something like this before, and honestly cannot decipher how to do so in any of the documentation. Help?

**Comment by jacobian** [comment]
Yeah sorry, they're very much not written with average people in mind -- this is very much still "works on my machine" code. I hope to maybe get there some day, but haven't been working on this lately.
