### ISSUE TITLE
Still working in 2020?

### ISSUE THREAD

**Issue by joshuaseltzer** [jacobian/overcast-sonos#14]
I'm attempting to run this on a server (with Python 3.7) and it works for a few of my Podcasts, but for most of them, I get an "unable to connect to Overcast" on from the Sonos Controller.

Should this still be working in 2020? I had to make a few changes to adapt it for Python 3.7, and I'm actually running slightly newer versions of the requirements.  I'm unsure if that's causing problems, but the server itself appears to be working as intended, based on the logs.

**Comment by jacobian** [comment]
I sort of doubt it. I haven't worked on this in a while, and I wouldn't be surprised if either Sonos or Overcast made changes that broke it.

**Comment by joshuaseltzer** [comment]
Well, based on the logs, it seems to be working correctly...it's pulling all of my podcasts correctly, displaying the correct artwork, etc.  In fact a few of my podcasts actually play correctly, but then there's a majority of them that simply refuse to play.

The URLs it's returning seem valid - I throw them into my web browser, and it plays at the correct offset and everything.

I'm attempting to set up a new Python virtualenv with Python 2.7, in the hopes that will allow it to work correctly.

**Comment by joshuaseltzer** [comment]
Looks like it's working with Python 2.7! Guessing something in Python 3 wasn't working 100% with your code.  Going to close this now...thanks for putting together this project!
