### ISSUE TITLE
ImportError: No module named requests

### ISSUE THREAD

**Issue by dan-todd** [jacobian/overcast-sonos#4]
Hi,

Very keen to get this project working! I've run:

`OVERCAST_USERNAME=dan@diffusions.net OVERCAST_PASSWORD=xxx python overcast-sonos.py`

but get 

```
Traceback (most recent call last):
  File "overcast-sonos.py", line 4, in <module>
    from overcast import Overcast, utilities
  File "/Applications/overcast-sonos/overcast.py", line 7, in <module>
    import requests
ImportError: No module named requests
```

in return.

Any clues on how I might proceed? I've utterly new with Python.

Dan

**Comment by bbock** [comment]
Hi Dan,

python is missing required libraries. These should have been installed at the step

`pip install -r requirements.txt`

from the Readme. Maybe you missed that step or some errors happened during installation?

If you are using Debian or Ubuntu Linux, you need to install some dependencies first:

`apt-get install libxml2-dev libxslt-dev`

cheers
Bernhard

**Comment by antonino-u** [comment]
Hey @dan-todd, since @bbock answered you, I'm closing this issue.
