### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by multisonic** [jacobian/overcast-sonos#5]
After typing in `OVERCAST_USERNAME=[myemail] OVERCAST_PASSWORD=[mypassword] python overcast-sonos.py`, I'm getting the following, and the terminal hangs:

```
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): overcast.fm
DEBUG:requests.packages.urllib3.connectionpool:"POST /login HTTP/1.1" 302 None
INFO:requests.packages.urllib3.connectionpool:Resetting dropped connection: overcast.fm
DEBUG:requests.packages.urllib3.connectionpool:"GET /podcasts HTTP/1.1" 200 None
INFO:overcast-sonos:at=start
```

Any advice? Thanks for creating this!

**Comment by antonino-u** [comment]
Doesn't look like a hang, that's how it's supposed to work. Are you having trouble connecting to the service?

**Comment by multisonic** [comment]
Got it. When I go to the Sonos app, I get "Unable to browse music - there
was a problem connecting to Overcast".

--
Michael P. Zaleski

**Comment by multisonic** [comment]
Found my issue. All set!

**Comment by officehax-personal** [comment]
What was this issue? I am having the same problem:
"Unable to browse music - there was a problem connecting to Overcast"

**Comment by officehax-personal** [comment]
silly mistake on my part. I was using the Sonos IP address instead of my IP address for:
Endpoint URL and Secure Endpoint URL: http://<YOUR_IP>:8140/overcast-sonos
