### ISSUE TITLE
Track duration, resumable, and time reporting issues

### ISSUE THREAD

**Issue by kjellr** [jacobian/overcast-sonos#6]
Up until recently, `overcast-sonos` had been doing an awesome job of tracking the time for each podcast, syncing with Overcast, and resuming episodes. Over the past few days though, that's stopped working for me. 

Playing episodes now displays a crazy episode length:

<img width="259" alt="screen shot 2017-02-23 at 9 03 47 am" src="https://cloud.githubusercontent.com/assets/1202812/23262040/4894e2fc-f9a7-11e6-998e-19d12a17feaa.png">

Soon after the episode starts playing, it's marked as played and removed from Overcast's Active Episodes list. Everything else is working as expected.

This behavior seemed to coincide with the release of [Overcast 3](https://marco.org/2017/02/20/overcast3), so I'm not sure if there were some under-the-hood Overcast changes that broke this integration?

Let me know if there's anything else I can provide. 

cc @antonino-u, since it looks like you'd recently spent time on this stuff (thank you!).

**Comment by antonino-u** [comment]
Ahh I'm on vacation right now without any Sonos speakers and I will fix this once I'm back home early next week! Rest assured that if it's broken for you, it's broken for me. Assigning myself to this in the meantime, thanks for the heads up. I was actually wondering if Overcast 3 broke anything!

**Comment by kjellr** [comment]
Sounds good. I'm happy to help test a PR when you're ready — feel free to ping me. Thanks again!

**Comment by antonino-u** [comment]
I have a PR here: #7
Basically Overcast/Marco changed the way duration strings show up on the frontend so it now limits our ability to have a proper duration. Instead of "hh:mm:ss' we now have to parse 'xx min'. 
For now I've left the calculation to be just min * 60, but if we see that podcasts are ending early I'll add a minute or 30 seconds and we'll see if that's better.

**Comment by kjellr** [comment]
Thanks @antonino-u! 

I tested a few podcasts, and the endings varied. One ended while there were ~24 seconds left on the clock, and the rest hit the 0:00 mark but kept playing for between 1 – 2:30 minutes until they actually ended. 

I did encounter a couple issues with this:

1. The episode that ended _before_ the time clock ([this one](https://overcast.fm/+lwxuNA/)) didn't get removed from "Active Episodes." Replaying the episode would fail, since `overcast-sonos` thought I'd already played the whole thing. 
2. The episodes that kept playing _after_ the timer ended were removed from "Active Episodes" before I'd listened to the whole thing. This wasn't a huge deal, since each time there were under a few minutes left.

**Comment by kjellr** [comment]
I've been testing this for a little over a week now, and it's been fine in practice. I've run into a couple more instances when the episode wasn't marked as finished in Overcast because it ended before our clock ran out, but in those cases I just removed the episode manually. 

Given the new constraints, I think this is probably our best option. Thanks @antonino-u for the quick fix. 👏

**Comment by antonino-u** [comment]
I've also been testing it, and I think at least for the time being this is the best we can do, sadly :( 
I merged the branch back into master!
