### ISSUE TITLE
Update the Overcast app icon.

### ISSUE THREAD

**Issue by kjellr** [jacobian/overcast-sonos#8]
This is very minor, but I noticed we're still pulling in an old version of the Overcast icon from the App store (it was refreshed in Overcast v3). 

Old: 
![175x175bb-old](https://cloud.githubusercontent.com/assets/1202812/25313942/710cecd2-2807-11e7-97de-b68f67a2c9e1.jpg)

New:
![175x175bb-new](https://cloud.githubusercontent.com/assets/1202812/25313945/73f42a64-2807-11e7-81e3-3741f5bc2968.jpg)

It's a quick fix: we just need to swap out the app store URLs for the icon. [This diff should take care of it.](https://gist.github.com/kjellr/77cc4af11a12a467ffd973451fd48fe3)

**Comment by antonino-u** [comment]
Love the attention to detail :) 
I'm at work right now, if you could make this a PR i'll approve and merge it right away!
